DATA_FORM = {
    "brand": "Samsung",
    "model": "",
    "released_min": "2018-01-01",
    "released_max": "",
    "design": "",
    "manufacturer": "",
    "codename": "",
    "oemid": "",
    "hw_e[]": "0",
    "cat": "131",
    "width_min": "",
    "width_max": "",
    "width_i_min": "",
    "width_i_max": "",
    "height_min": "",
    "height_max": "",
    "height_i_min": "",
    "height_i_max": "",
    "depth_min": "",
    "depth_max": "",
    "depth_i_min": "",
    "depth_i_max": "",
    "volume_min": "",
    "volume_max": "",
    "mass_min": "",
    "mass_max": "",
    "mass_oz_min": "",
    "mass_oz_max": "",
    "os_family": "141",
    "os[]": ["422","453","464","468","480","491","383","404"],
    "sw_e[]": "0",
    "cpu_clk_min": "",
    "cpu_clk_max": "",
    "ram_type": "1",
    "ram_clk_min": "",
    "ram_clk_max": "",
    "ram_cap_min": "",
    "ram_cap_max": "",
    "ram_cap_b": "",
    "ram_free_min": "",
    "ram_free_max": "",
    "ram_chip": "",
    "rom_type": "0",
    "rom_if": "0",
    "rom_cap_min": "",
    "rom_cap_max": "",
    "rom_cap_b": "",
    "rom_chip": "",
    "rom2_cap_min": "",
    "rom2_cap_max": "",
    "rom2_cap_b": "",
    "hdd_cap_min": "",
    "hdd_cap_max": "",
    "d_notch_min": "",
    "d_notch_max": "",
    "d_hole_min": "",
    "d_hole_max": "",
    "d_diag_i_min": "",
    "d_diag_i_max": "",
    "d_px_min": "",
    "d_px_max": "",
    "d_py_min": "",
    "d_py_max": "",
    "d_bezel_min": "",
    "d_bezel_max": "",
    "d_util_min": "",
    "d_util_max": "",
    "d_ppi_min": "",
    "d_ppi_max": "",
    "d_type": "0",
    "d_subtype[]": "0",
    "d_depth_min": "",
    "d_depth_max": "",
    "d_dr_min": "",
    "d_dr_max": "",
    "d_lit": "0",
    "d_refl": "0",
    "d_subpixel": "0",
    "d_refresh_min": "",
    "d_refresh_max": "",
    "d_sr": "0",
    "d2_diag_i_min": "",
    "d2_diag_i_max": "",
    "d2_px_min": "",
    "d2_px_max": "",
    "d2_py_min": "",
    "d2_py_max": "",
    "d2_type": "0",
    "d2_depth_min": "",
    "d2_depth_max": "",
    "d2_dr_min": "",
    "d2_dr_max": "",
    "d2_refresh_min": "",
    "d2_refresh_max": "",
    "graphics_chip": "",
    "gpu_clk_min": "",
    "gpu_clk_max": "",
    "av_out_type": "0",
    "av_out_c": "0",
    "av_out_res": "0",
    "av_in_type": "0",
    "av_in_c": "0",
    "au_ch": "0",
    "au_chip": "",
    "au_ad_min": "",
    "au_ad_max": "",
    "au_ad_sr_min": "",
    "au_ad_sr_max": "",
    "mic": "0",
    "au_in": "0",
    "au_da_min": "",
    "au_da_max": "",
    "au_da_sr_min": "",
    "au_da_sr_max": "",
    "speaker": "0",
    "speaker_pwr_min": "",
    "speaker_pwr_max": "",
    "au_out": "0",
    "p_net[]": "0",
    "p_r[]": "0",
    "p_card[]": "0",
    "ring": "0",
    "hac[]": "0",
    "p_e[]": "0",
    "p_chip": "",
    "p_dual": "0",
    "p2_r[]": "0",
    "p2_card[]": "0",
    "ts": "0",
    "ts_points": "0",
    "ts_sr_min": "",
    "ts_sr_max": "",
    "tp": "0",
    "tp_points": "0",
    "kb": "0",
    "kb_bl": "0",
    "kb_num_min": "",
    "kb_num_max": "",
    "dpad": "0",
    "jog": "0",
    "exp[]": "0",
    "usb_v": "0",
    "usb_r[]": "0",
    "usb_e[]": "0",
    "usb_c": "0",
    "usb_chr_p_min": "",
    "usb_chr_p_max": "",
    "bt": "0",
    "bt_p[]": "0",
    "bt_chip": "",
    "wlan[]": "0",
    "wlan_e[]": "0",
    "wlan_chip": "",
    "wman[]": "0",
    "nfc[]": "0",
    "ir": "0",
    "ir_r": "0",
    "ser": "0",
    "ser_c": "0",
    "ser_r": "0",
    "lan": "0",
    "lan_c": "0",
    "modem": "0",
    "modem_c": "0",
    "fax": "0",
    "tv[]": "0",
    "tv_a": "0",
    "radio_rx": "0",
    "radio_a": "0",
    "radio_tx": "0",
    "dmb[]": "0",
    "dmb_a": "0",
    "gps[]": "0",
    "gps_ch_min": "",
    "gps_ch_max": "",
    "gps_a": "0",
    "gps_e[]": "0",
    "glonass[]": "0",
    "galileo[]": "0",
    "bds[]": "0",
    "n_chip": "",
    "c_module": "",
    "c_sensor": "0",
    "c_format_min": "",
    "c_format_max": "",
    "c_p_size_min": "",
    "c_p_size_max": "",
    "c_px_min": "",
    "c_px_max": "",
    "c_py_min": "",
    "c_py_max": "",
    "c_pn": "",
    "c_apert_w_min": "",
    "c_apert_w_max": "",
    "c_apert_t_min": "",
    "c_apert_t_max": "",
    "c_zoom_min": "",
    "c_zoom_max": "",
    "c_dzoom_min": "",
    "c_dzoom_max": "",
    "c_focus[]": "0",
    "c_efl_min_min": "",
    "c_efl_min_max": "",
    "c_efl_max_min": "",
    "c_efl_max_max": "",
    "c_vpx_min": "",
    "c_vpx_max": "",
    "c_vpy_min": "",
    "c_vpy_max": "",
    "c_flash": "0",
    "c_e[]": "0",
    "cd_sensor": "0",
    "cd_module": "",
    "cd_p_size_min": "",
    "cd_p_size_max": "",
    "cd_px_min": "",
    "cd_px_max": "",
    "cd_py_min": "",
    "cd_py_max": "",
    "cd_pn": "",
    "cd_apert_w_min": "",
    "cd_apert_w_max": "",
    "cd_focus[]": "0",
    "cd_e[]": "0",
    "cd2_sensor": "0",
    "cd2_px_min": "",
    "cd2_px_max": "",
    "cd2_py_min": "",
    "cd2_py_max": "",
    "cd2_pn": "",
    "cd2_apert_w_min": "",
    "cd2_apert_w_max": "",
    "cd3_sensor": "0",
    "cd4_sensor": "0",
    "c2_loc": "0",
    "c2_module": "",
    "c2_sensor": "0",
    "c2_format_min": "",
    "c2_format_max": "",
    "c2_p_size_min": "",
    "c2_p_size_max": "",
    "c2_px_min": "",
    "c2_px_max": "",
    "c2_py_min": "",
    "c2_py_max": "",
    "c2_pn": "",
    "c2_apert_w_min": "",
    "c2_apert_w_max": "",
    "c2_focus[]": "0",
    "c2_vpx_min": "",
    "c2_vpx_max": "",
    "c2_vpy_min": "",
    "c2_vpy_max": "",
    "c2_flash": "0",
    "c2_e[]": "0",
    "c2d_sensor": "0",
    "c2d_p_size_min": "",
    "c2d_p_size_max": "",
    "c2d_px_min": "",
    "c2d_px_max": "",
    "c2d_py_min": "",
    "c2d_py_max": "",
    "c2d_apert_w_min": "",
    "c2d_apert_w_max": "",
    "c2d2_sensor": "0",
    "c2d2_px_min": "",
    "c2d2_px_max": "",
    "c2d2_py_min": "",
    "c2d2_py_max": "",
    "c2d2_apert_w_min": "",
    "c2d2_apert_w_max": "",
    "compass": "0",
    "acc": "0",
    "gyro": "0",
    "sensor[]": "0",
    "bcs[]": "0",
    "ipf": "1",
    "ips": "1",
    "ipt_min": "",
    "ipt_max": "",
    "ipi_min": "",
    "ipi_max": "",
    "ipit_min": "",
    "ipit_max": "",
    "mil": "0",
    "b_type": "0",
    "b_build": "0",
    "b_cell_min": "",
    "b_cell_max": "",
    "b_volt_res_min": "",
    "b_volt_res_max": "",
    "b_cap_res_min": "",
    "b_cap_res_max": "",
    "b_energy_min": "",
    "b_energy_max": "",
    "b_time_min": "",
    "b_time_max": "",
    "b_time_sby_min": "",
    "b_time_sby_max": "",
    "b_time_talk_min": "",
    "b_time_talk_max": "",
    "wlc[]": "0",
    "wlc_chr_p_min": "",
    "wlc_chr_p_max": "",
    "country[]": "0",
    "region[]": "0",
    "result_lower_limit":0
    }



HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "fa,en-US;q=0.9,en;q=0.8",
    "Cache-Control": "max-age=0",
    "Connection": "keep-alive",
    "Content-Type": "application/x-www-form-urlencoded",
    "Origin": "https://phonedb.net",
    "Referer":"https://phonedb.net/index.php?m=device&s=query&d=detailed_specs" ,
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0",
    "sec-ch-ua": "\"Not;A=Brand\";v=\"99\", \"Microsoft Edge\";v=\"139\", \"Chromium\";v=\"139\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\""
}

SSL_CRT_STRING = """
-----BEGIN CERTIFICATE-----
MIIEszCCA5ugAwIBAgIQCyWUIs7ZgSoVoE6ZUooO+jANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
MjAeFw0xNzExMDIxMjI0MzNaFw0yNzExMDIxMjI0MzNaMGAxCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xHzAdBgNVBAMTFlJhcGlkU1NMIFRMUyBSU0EgQ0EgRzEwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQC/uVklRBI1FuJdUEkFCuDL/I3aJQiaZ6aibRHj
ap/ap9zy1aYNrphe7YcaNwMoPsZvXDR+hNJOo9gbgOYVTPq8gXc84I75YKOHiVA4
NrJJQZ6p2sJQyqx60HkEIjzIN+1LQLfXTlpuznToOa1hyTD0yyitFyOYwURM+/CI
8FNFMpBhw22hpeAQkOOLmsqT5QZJYeik7qlvn8gfD+XdDnk3kkuuu0eG+vuyrSGr
5uX5LRhFWlv1zFQDch/EKmd163m6z/ycx/qLa9zyvILc7cQpb+k7TLra9WE17YPS
n9ANjG+ECo9PDW3N9lwhKQCNvw1gGoguyCQu7HE7BnW8eSSFAgMBAAGjggFmMIIB
YjAdBgNVHQ4EFgQUDNtsgkkPSmcKuBTuesRIUojrVjgwHwYDVR0jBBgwFoAUTiJU
IBiV5uNu5g/6+rkS7QYXjzkwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsG
AQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMDQGCCsGAQUFBwEB
BCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEIGA1Ud
HwQ7MDkwN6A1oDOGMWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEds
b2JhbFJvb3RHMi5jcmwwYwYDVR0gBFwwWjA3BglghkgBhv1sAQEwKjAoBggrBgEF
BQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzALBglghkgBhv1sAQIw
CAYGZ4EMAQIBMAgGBmeBDAECAjANBgkqhkiG9w0BAQsFAAOCAQEAGUSlOb4K3Wtm
SlbmE50UYBHXM0SKXPqHMzk6XQUpCheF/4qU8aOhajsyRQFDV1ih/uPIg7YHRtFi
CTq4G+zb43X1T77nJgSOI9pq/TqCwtukZ7u9VLL3JAq3Wdy2moKLvvC8tVmRzkAe
0xQCkRKIjbBG80MSyDX/R4uYgj6ZiNT/Zg6GI6RofgqgpDdssLc0XIRQEotxIZcK
zP3pGJ9FCbMHmMLLyuBd+uCWvVcF2ogYAawufChS/PT61D9rqzPRS5I2uqa3tmIT
44JhJgWhBnFMb7AGQkvNq9KNS9dd3GWc17H/dXa1enoxzWjE0hBdFjxPhUb0W3wi
8o34/m8Fxw==
-----END CERTIFICATE-----
"""